version: 2
jobs:
  test_django3:
    docker:
      - image: cimg/python:3.6.15
    steps:
      - checkout
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            make test_requirements
            pip install django==3.0.3
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest
            codecov
  test_django2:
    docker:
      - image: cimg/python:3.6.15
    steps:
      - checkout
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            make test_requirements
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest
            codecov

  flake8:
    docker:
    - image: cimg/python:3.6.15
    steps:
    - checkout
    - run:
        name: Run flake8
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install flake8
          flake8 . --exclude=venv

  publish_to_pypi:
    docker:
    - image: cimg/python:3.6.15
    steps:
    - checkout
    - run:
        command: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          make test_requirements
          make publish

workflows:
  version: 2
  test_and_publish_to_pypi:
    jobs:
      - test_django3
      - test_django2
      - flake8
      - publish_to_pypi:
          requires:
          - test_django3
          - test_django2
          filters:
            branches:
              only: master
