version: 2
jobs:
  test_django3:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade --no-cache-dir pip
            make test_requirements
            pip install --no-cache-dir django==3.2.25
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest
            codecov

  test_django4:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade --no-cache-dir pip
            make test_requirements
            pip install --no-cache-dir django==4.2.13
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest
            codecov

  test_django5:
    docker:
      - image: cimg/python:3.12.3
    steps:
      - checkout
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade --no-cache-dir pip
            make test_requirements
            pip install --no-cache-dir django==5.0.6
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest
            codecov

  flake8:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir flake8
            flake8 . --exclude=venv

  publish_to_pypi:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install --upgrade --no-cache-dir pip
            make test_requirements
            make publish

workflows:
  version: 2
  test_and_publish_to_pypi:
    jobs:
      - test_django3
      - test_django4
      - test_django5
      - flake8
      - publish_to_pypi:
          requires:
            - test_django3
            - test_django4
          filters:
            branches:
              only: master
